name: CI Pipeline

on:
  push:
    paths:
      - 'app/**'
      - 'run.py'
      - 'tests/**'
      - 'Dockerfile'
      - 'Makefile'
  workflow_dispatch: # allows manual trigger

jobs:
  ci:
    runs-on: self-hosted

    env:
      VERSION: 1.0.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run Tests
        run: make test

      - name: Run Code Linting
        run: make lint

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build
        run: make build-api

      - name: Push Docker Image
        run: |
          docker tag student-api:${{ env.VERSION }} ${{ secrets.DOCKER_REGISTRY }}/student-api:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/student-api:${{ env.VERSION }}
